version: '3'

services:
  display:
    container_name: lushroom-display
    privileged: true
    network_mode: host
    image: "lushdigital/lushroom-display:staging"
    volumes:
      - /media/usb:/media/usb
      - /dev/fb0:/dev/fb0
      - /dev/input/event0:/dev/input/event0
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - HOSTNAME
      - SENTRY_URL=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137
    restart: always

  player:
    container_name: lushroom-player
    image: "lushdigital/lushroom-player:staging"
    privileged: true
    depends_on:
      - brickd
    ports:
      - 8080:80
    volumes:
      # - /home/lush/lrpi_player/flask/:/opt/code/flask:ro
      - /media/usb:/media/usb
      - /dev/vchiq:/dev/vchiq
      - /opt/vc:/opt/vc
    environment:
      - BRICKD_HOST=brickd
      - SENTRY_URL=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137

  nginx:
    image: nginx:latest
    container_name: lushroom-nginx
    depends_on:
      - scentroom
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  scentroom:
    image: "lushdigital/lushroom-scentroom:staging"
    container_name: lushroom-scentroom
    privileged: true
    depends_on:
      - player
      - brickd
    volumes:
      - /media/usb:/media/usb
    environment:
      - PORT=5000
    command: python3 -u FlaskFileUploader.py

  brickd:
    image: "lushdigital/lushroom-brickd:staging"
    container_name: lushroom-brickd
    privileged: true
    ports:
       - 4223:4223
    restart: always